apiVersion: apps/v1
kind: Deployment
metadata:
  name: academix-deployment
  labels:
    app: academix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academix
  template:
    metadata:
      labels:
        app: academix
    spec:
      containers:
        - name: academix
          image: byab5/ht2024-api_service:0.2.0-SNAPSHOT
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: academix-service
spec:
  type: LoadBalancer
  selector:
    app: academix
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080